### ISSUE TITLE
Default or enforced values for MJD min and max

### ISSUE THREAD

**Issue by thespacedoctor** [lukeshingles/atlasserver#1]
Small niggle - the request throws an error if I don't add min/max MJD values.

[![](https://live.staticflickr.com/65535/50546974541_4fe7200fdc_z.png)](https://live.staticflickr.com/65535/50546974541_4fe7200fdc_o.png)

Solutions could be to either enforce the input in the HTML form or pre-populate with a default ~1 month window (min = 1 month ago, max = today)

**Comment by lukeshingles** [comment]
This is now implemented. The two values on a line will need to be separated by a comma if spaces are required for the RA column. I'm still working on improving the help messsages and form validation handling.
