### ISSUE TITLE
columns mag5sig and ZP

### ISSUE THREAD

**Issue by ale-munozarancibia** [lukeshingles/atlasserver#10]
Great tool! I have a question about one of the columns in the output file, mag5sig. This column is not defined in https://fallingstar-data.com/forcedphot/resultdesc/. On the contrary, ZP is defined, but does not appear in the output file. Which of these columns should be displayed?

**Comment by lukeshingles** [comment]
Thanks for finding the inconsistency. The data files are generated through by an external program, which was updated to replace the "zero point" column with the "five-sigma limiting magnitude" column. The columns in the data files should be the correct ones, and I have updated the web page to describe to the current file format.
