### ISSUE TITLE
Reference Images for Forced Photometry

### ISSUE THREAD

**Issue by dmvandam** [lukeshingles/atlasserver#13]
Loving this program, it's very helpful, and I'm using it now with great pleasure.

Given the fact that this is forced photometry I'm wondering if is possible to see a reference image to make sure that you are properly locked onto the star. The reason I say this is because I'm currently working on a star that depending on the catalogue is located at xx:xx:xx.xx -xx:xx:xx.5 or xx:xx:xx.xx -xx:xx:xx.6 (i.e. a 100 mas difference) makes a small, but significant, difference in the light curve (see attached).

This is the Dec=X.5
[dec=x.5.pdf](https://github.com/lukeshingles/atlasserver/files/6318366/dec.x.5.pdf)

This is the Dec=X.6
[dec=x.6.pdf](https://github.com/lukeshingles/atlasserver/files/6318365/dec.x.6.pdf)

Specifically of interest is the dip at MJD~59000, where though visible in both files, the Dec=X.6 one shows the dip in both filters, where as Dec=X.5 shows it only in the o filter. It would be nice to validate that you've selected the right location, by seeing an ATLAS postcard (be it 250x250 pixels or something like this... enough that it works as a finder chart) with a cross at the specified location.

Kind regards,
Dirk

**Comment by lukeshingles** [comment]
Hi Dirk. Thanks for the feedback. I agree that this feature would be a nice addition, but might not be so straightforward for me to implement on my own (I handle the web interface part). I'll discuss it with @genghisken and see if we can get it added in at some point.

**Comment by lukeshingles** [comment]
@dmvandam, I've added new image request buttons that will provide a ZIP file constaing FITS images and JPEGs for the first 500 exposures in the forced photometry results. If you get a chance to try it out, please let me know if this is helps to resolve your targeting problem.

**Comment by dmvandam** [comment]
@lukeshingles this is fantastic, this is great and works really well. Really nice feature that you've included the ability to download the images on an old query. I'm really happy with the addition and how quickly you were able to pick this up!
