### ISSUE TITLE
Populate the Forced Photometry Server FAQ

### ISSUE THREAD

**Issue by genghisken** [lukeshingles/atlasserver#14]
The question about difference flux over long periods, step changes in the photometry, and possible mitigations comes up *all the time*.  Can we turn this into an FAQ please?  (See recent email about this.)  There's only one FAQ on our FAQ page!

**Comment by lukeshingles** [comment]
Do you want to suggest a particular wording for the Q and A, or should I attempt to generalise it myself?

**Comment by genghisken** [comment]
Maybe something like:

Q: Why are there step discontinuities in the difference flux lightcurve when requested over a long period of time (e.g. years)?

A: The difference image reference templates are periodically replaced.  In order to see whether the step change is real you might want to consider requesting "reduced" (i.e. input) image data.  If there are no discontinuities in this lightcurve, the likelihood is that the step features are present because of the template change.
