### ISSUE TITLE
Clicking on a /queue/ link should redirect to login/register if you are logged out or unregistered

### ISSUE THREAD

**Issue by genghisken** [lukeshingles/atlasserver#15]
Redirect (to login / register page) should happen if you log out and go straight to the:

https://fallingstar-data.com/forcedphot/queue/

link (and anything underneath that).  Easily reproducible.  Log out, and click the above link.  Current behaviour shows a pop-up window asking for "basic authentication" credentials.  Confuses a lot of people when I send links to a specific forced phot object.

Would be really nice if it:

* redirected to the login/registration page if the person is not logged in
* redirected after that to the actual link you were going to in the first place after logging in (instead of having to re-click the link)

**Comment by lukeshingles** [comment]
Thanks for the feedback, Ken. Please give the new system a try when you get a chance. I've done as you suggested, but also allowed anonymous users to view tasks now. There was no particular reason to require a login for that, I just hadn't customised the permission model.
