### ISSUE TITLE
Image stamp prevents lightcurve being viewed across full screen

### ISSUE THREAD

**Issue by genghisken** [lukeshingles/atlasserver#17]
The image stamp that now appears top right of every request prevents the lightcurve from being viewed across the full width of a page.

E.g.:

https://fallingstar-data.com/forcedphot/queue/86781/

Even requests which I could previously view the lightcurve across the page are no longer viewable that way.  I'm guessing there's a new bootstrap column for the image contents.

**Comment by lukeshingles** [comment]
Could you add a screenshot of what you are seeing? The lightcurve is displaying as expected for me on Chrome and Safari.

**Comment by genghisken** [comment]
Interesting... When I first click the link I get this... (I'm using Safari.)

![Screenshot 2021-08-24 at 10 49 58](https://user-images.githubusercontent.com/5502468/130596314-32f7f63d-c6d0-43f4-979d-8265bb8f375c.png)

But when I refresh the page, I get this...

![Screenshot 2021-08-24 at 10 50 20](https://user-images.githubusercontent.com/5502468/130596416-e58b8eb3-a357-484e-bf63-bacb4663c554.png)

**Comment by lukeshingles** [comment]
Perhaps some old javascript code was cached? Try a shift + refresh in Safari. Does the problem come back or did the refresh fix it for new pages as well?

**Comment by genghisken** [comment]
Looks like I had some old cached javascript.  Shift-refresh seemed to fix it.  I've closed the issue!  Thanks.
