### ISSUE TITLE
Job Queue information - display User's own submitted jobs

### ISSUE THREAD

**Issue by smarttgit** [lukeshingles/atlasserver#2]
On the "Job Queue" information displayed 

Need to have it so that a user can only see their own jobs in the queue. 

At present any user can see all jobs submitted. And they can also delete anyone else's job. Just display the user's own jobs

**Comment by lukeshingles** [comment]
Thanks for the feedback. I've changed the queue to only show the current user's tasks. Please close the issue if this is working as expected.

**Comment by mFulton07** [comment]
I only see my job requests now. Does someone else want to confirm their side before closing this ticket?
