### ISSUE TITLE
MJD Suggestion 

### ISSUE THREAD

**Issue by thomasmoore-42** [lukeshingles/atlasserver#23]
Hi Luke, great tool and I use it a lot for SN. It might be good to include the current MJD as the default MJD Max for the forced requests or a 'use current MJD' button. I know it would just save a few clicks. Just an ease of use note but it might be nice since I regularly have to check the current MJD when following SN.

**Comment by mFulton07** [comment]
Hi Thomas, the tool already does this in a sense. If you don't specify either of the Min or Max MJDs it will assume you want for all time. 

Here is an example where I didn't specify the Max MJD. Note how it puts in an infinite sign: https://fallingstar-data.com/forcedphot/queue/195767/.

**Comment by thomasmoore-42** [comment]
Thanks for your response Michael - It seems I have been doing this manually this whole time. Thanks for letting me know!

**Comment by lukeshingles** [comment]
Hi, thanks @thomasmoore-42 for the feedback and @mFulton07 for the response. As Michael pointed out, a blank MJD max will fetch the latest data, but this is not obvious from looking at the input form. I'm just reopening this issue to say that I've made an update to the form that will hopefully make this behaviour clear.
