### ISSUE TITLE
Documentation for MPC objects - and front page update

### ISSUE THREAD

**Issue by genghisken** [lukeshingles/atlasserver#27]
From Larry:

The fact that the forced photometry server supports moving objects is not obvious from the documentation.  Can you put a blurb on the front page of the server and in the FAQ that explains how moving objects are supported?

A caveat should be added somewhere that says that only objects with good orbits will work properly, e.g. numbered and multi-opposition objects.  With comets, YMMV because of comae, fragments, etc.

From Ken:

Front page blurb also needs updating (e.g. no longer limited to dec > -50 degrees). Happy to do that myself if necessary!

(We can iterate on the documentation!)

**Comment by lukeshingles** [comment]
I personally don't understand what can go in the MPC name box. I just pass the name string on to ssforce.sh which either returns some data or fails. Could someone write an FAQ entry for this topic and I'll put it on the site?
