### ISSUE TITLE
Form is re-submitted when refreshing webpage

### ISSUE THREAD

**Issue by mFulton07** [lukeshingles/atlasserver#3]
Refreshing the page (using the refresh button) after creating a request will resubmit the previous request (if they click continue on the resubmission warning) even when there is nothing filled in the request form. However, you cannot view the results of your request(s) without refreshing the page (either by the refresh button or reentering the URL or leaving the queue tab).

The form info is clearly being stored somewhere, though it is not visible on UI. Might want to consider clearing this store once the user clicks the submit request button.

**Comment by lukeshingles** [comment]
Thanks for finding this. I'd appreciate if you could take another look and close this issue if I've fixed it.

**Comment by mFulton07** [comment]
Yes perfect! Refreshing the webpage (with the refresh button) no longer triggers a resubmission of the previous request.
