### ISSUE TITLE
"Recover Account" Option when signing in

### ISSUE THREAD

**Issue by mFulton07** [lukeshingles/atlasserver#4]
Not really an issue, more of a request for a new feature.

I have forgotten my username and password, so now I am stuck at the login page. Maybe we can add a "recover account" option after a few failed login attempts?

If we aren't storing any sensitive information, it might be okay to just send an email containing the user's account details, rather than have them make a new password. To get account verification for the recover request, we could have them enter the email address used to register the account, but we might need extra security steps here...

**Comment by lukeshingles** [comment]
Thanks for the feedback. I've added a 'Forgot password' link to the login page. Try it out and let me know if there are any problems.

Also on the to-do list: email confirmation during registration and a 'password change' page.

**Comment by mFulton07** [comment]
Works great! I was able to reset the password and can now log in.
