### ISSUE TITLE
Error: No data returned

### ISSUE THREAD

**Issue by jowborowska** [lukeshingles/atlasserver#41]
Every attempt to produce the data ends with "Error: No data returned"
<img width="648" alt="Screen Shot 2023-11-24 at 09 00 34" src="https://github.com/lukeshingles/atlasserver/assets/54434838/da402167-2503-46d4-ab0e-6e0bf4e7c097">

**Comment by lukeshingles** [comment]
Thanks for alerting me to the issue. It looks like the database server is offline in Hawaii, but there's nothing I can do from my side except to report the problem (which I've just done now).
