### ISSUE TITLE
Queue problem

### ISSUE THREAD

**Issue by SaraFaris452** [lukeshingles/atlasserver#50]
I've requested forced photometry [Task 1227354], but it's taking too long (for every task I request). This problem also happened yesterday with a task I've canceled. Is there any problem with the server?

**Comment by lukeshingles** [comment]
Hello, thanks for the notice. The task runner was crashing when trying to send emails (SSL certificate problem on the new server), which prevented the jobs from completing. I've fixed the crashing and task 1227354 has now completed. Please re-open the issue if you continue to see problems.
