### ISSUE TITLE
Task links in the email

### ISSUE THREAD

**Issue by igorandreoni** [lukeshingles/atlasserver#6]
In the notification email, I receive the same link from all tasks that were submitted in the same request. For instance:

Task 3658: RA 264.64519 Dec 1.42066 img_difference 
https://fallingstar-data.com/forcedphot/queue/3659/
 comment: 'First two candidates in the source list.'
Task 3659: RA 30.6392 Dec 55.41712 img_difference 
https://fallingstar-data.com/forcedphot/queue/3659/
 comment: 'First two candidates in the source list.'

I imagine that you want the links above to be:
https://fallingstar-data.com/forcedphot/queue/3658/
https://fallingstar-data.com/forcedphot/queue/3659/

**Comment by lukeshingles** [comment]
Thanks for finding this bug. It has now been fixed.
