### ISSUE TITLE
Server error (500)

### ISSUE THREAD

**Issue by igorandreoni** [lukeshingles/atlasserver#7]
For task 3658 and 3660, which correspond to the same coordinates, I see an error message in the output PDF:

Server Error (500)

Why does the processing fail at these coordinates? Can an explanation be displayed in the PDF instead of the error message?

Task 3658
Comment: First two candidates in the source list. Request time 6:53pm
RA Dec: 264.64519 1.42066
Images: Difference
MJD range: [59184.0, ∞]
Queued at 2020-12-31 02:53:01 UTC
Finished at 2020-12-31 02:53:09 UTC

**Comment by genghisken** [comment]
Hi Igor

Yes - agreed! We need a friendly message to indicate that there is no data in that requested time period. (Object is behind the sun!)  The default start MJD is the current date minus 30 days.  Try an earlier start date (e.g. minus 130 days at 59084).

**Comment by lukeshingles** [comment]
I've made the error message slightly more helpful, but I think longer term I should mark requests that did't return any data and signal that in the queue cards.

**Comment by lukeshingles** [comment]
The task list now states if no data was returned by the request.
